version: '3'
services:
  nginx:
    container_name: nginx
    build: nginx/
    restart: always
    links:
      - api
      - mongo
  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
     - "9001:8080"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "9002:27017"
    volumes:
      - "mongodata:/data/db"


volumes:
   mongodata: